version: "3.8"

services:
  loki:
    build:
      context: ./loki
      dockerfile: Dockerfile
    image: loki:custom
    container_name: loki
    user: "472"
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    restart: unless-stopped

  promtail:
    build:
      context: ./promtail
      dockerfile: Dockerfile
    image: promtail:custom
    container_name: promtail
    user: "472"
    depends_on:
      - loki
    ports:
      - "9080:9080"
    # bind only the host logs; do NOT mount /etc/promtail (that would overwrite the config inside the image)
    volumes:
      - ./logs:/host-logs:ro
      - promtail-positions:/tmp
    restart: unless-stopped

volumes:
  loki-data:
  promtail-positions:
