import logging

logger = logging.getLogger(__name__)

MODELS = [
    "gpt-oss-120b",
    "gpt-oss-20b",
    "llama-4-scout-17b-16e-instruct",
    "llama-3.3-70b-instruct-fp8-fast",
    "llama-3.1-8b-instruct-fast",
    "aura-2-es",
    "aura-2-en",
    "granite-4.0-h-micro",
    "flux",
    "plamo-embedding-1b",
    "gemma-sea-lion-v4-27b-it",
    "indictrans2-en-indic-1B",
    "embeddinggemma-300m",
    "aura-1",
    "lucid-origin",
    "phoenix-1.0",
    "smart-turn-v2",
    "nova-3",
    "gemma-3-12b-it",
    "mistral-small-3.1-24b-instruct",
    "qwq-32b",
    "qwen2.5-coder-32b-instruct",
    "bge-reranker-base",
    "llama-guard-3-8b",
    "deepseek-r1-distill-qwen-32b",
    "llama-3.2-1b-instruct",
    "llama-3.2-3b-instruct",
    "llama-3.2-11b-vision-instruct",
    "flux-1-schnell",
    "llama-3.1-8b-instruct-awq",
    "llama-3.1-8b-instruct-fp8",
    "melotts",
    "llama-3.1-8b-instruct",
    "bge-m3",
    "meta-llama-3-8b-instruct",
    "whisper-large-v3-turbo",
    "llama-3-8b-instruct-awq",
    "llava-1.5-7b-hf",
    "una-cybertron-7b-v2-bf16",
    "embedding-100m",
    "semantic-text-similarity",
    "flux-1-dev",
    "deepseek-math-7b-instruct",
    "m2m100-1.2b",
    "whisper",
    "mistral-7b-instruct-v0.1",
    "gemma-7b-it",
    "stable-diffusion-xl-base-1.0",
    "starling-lm-7b-beta",
    "resnet-50",
    "bart-large-cnn",
    "qwen1.5-7b-chat-awq",
    "qwen1.5-14b-chat-awq",
    "qwen1.5-0.5b-chat",
    "stable-diffusion-xl-lightning",
    "dreamshaper-8-lcm",
    "stable-diffusion-v1-5-img2img",
    "stable-diffusion-v1-5-inpainting",
    "deepseek-coder-6.7b-instruct-awq",
    "deepseek-coder-6.7b-base-awq",
    "mistral-7b-instruct-v0.2",
    "detr-resnet-50",
    "bge-large-en-v1.5",
    "bge-base-en-v1.5",
    "bge-small-en-v1.5",
    "distilbert-sst-2-int8",
    "tinyllama-1.1b-chat-v1.0",
    "phi-2",
    "gemma-7b-it-lora",
    "gemma-2b-it-lora",
    "llama-2-7b-chat-fp16",
    "llama-2-7b-chat-int8",
    "neural-chat-7b-v3-1-awq",
    "mistral-7b-instruct-v0.2-lora",
    "zephyr-7b-beta-awq",
    "openchat-3.5-0106",
    "sqlcoder-7b-2",
    "whisper-tiny-en",
    "discolm-german-7b-v1-awq",
    "falcon-7b-instruct",
    "qwen1.5-1.8b-chat",
    "uform-gen2-qwen-500m",
    "llama-3-8b-instruct",
    "mistral-7b-instruct-v0.1-awq",
    "llama-3.2-11b-vision-instruct"
]

def all_models():
    return MODELS

def ensure_valid_model(model: str) -> str:
    if model not in MODELS:
        raise ValueError("model_not_found")
    return model
