name: n8n_stack

networks:
  edge: {}
  backplane:
    internal: false  # Change this to allow DNS resolution
    driver: bridge

volumes:
  n8n_data:

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:8081
      - --entrypoints.websecure.address=:8443
      - --log.level=INFO
      - --accesslog=true
      - --providers.file.directory=/dynamic
      - --providers.file.watch=true
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:8443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic:/dynamic:ro
      - ./traefik/certs:/certs:ro
    networks: [edge, backplane]

  n8n:
    build:
      context: ./n8n
    image: local/n8n-with-logs:latest
    pull_policy: build
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 9.9.9.9
    dns_opt:
      - timeout:2
      - attempts:3
    environment:
      - N8N_HOST=n8n.localtest.me
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.localtest.me:8443/
      - GENERIC_TIMEZONE=Asia/Kolkata
      - TZ=Asia/Kolkata
      - NODE_ENV=production
      - N8N_LOG_LEVEL=debug
      - N8N_LOG_OUTPUT=file
      - N8N_LOG_FILE_LOCATION=/var/log/n8n/n8n.log
      - N8N_LOG_FILE_SIZE_MAX=32
      - N8N_LOG_FILE_COUNT_MAX=30
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/local-files:/files
      - ./n8n/logs:/var/log/n8n
      - ./n8n/custom-nodes:/home/node/.n8n/custom-nodes
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`n8n.localtest.me`)
      - traefik.http.routers.n8n.entrypoints=web
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.http.routers.n8n-https.rule=Host(`n8n.localtest.me`)
      - traefik.http.routers.n8n-https.entrypoints=websecure
      - traefik.http.routers.n8n-https.tls=true
    networks: [edge, backplane]

  automation-api:
    build:
      context: ./automation-api
    image: local/automation-api:latest
    pull_policy: build
    restart: unless-stopped
    environment:
      - PORT=8080
      - N8N_BASE_URL=http://n8n:5678
      - N8N_WEBHOOK_PATH=/webhook/automation
    labels:
      - traefik.enable=true
      - traefik.http.routers.automation.rule=Host(`api.localtest.me`)
      - traefik.http.routers.automation.entrypoints=web
      - traefik.http.services.automation.loadbalancer.server.port=8080
    networks: [edge, backplane]