---
version: '3.8'

# Unified monitoring stack for all services
services:
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    profiles: ["monitoring"]  # Only starts with --profile monitoring
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring-network

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    profiles: ["monitoring"]  # Only starts with --profile monitoring
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring-network
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro  # Collect logs from all containers

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    profiles: ["monitoring"]  # Only starts with --profile monitoring
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring-network
    depends_on:
      - loki

# Shared volumes for monitoring data
volumes:
  grafana_data:
    driver: local

# Isolated network for monitoring services
networks:
  monitoring-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${MONITORING_SUBNET:-172.27.0.0/16}
