version: '3.8'

services:
  api:
    build: .
    container_name: rag-api
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - LOG_LEVEL=INFO
      - DATABASE_SUBNET=${DATABASE_SUBNET:-172.26.0.0/16}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      qdrant:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 2G
