# docker-compose.kafka.yml - CORRECTED VERSION
services:
  kafka:
    image: apache/kafka-native:latest
    container_name: kafka
    restart: unless-stopped
    environment:
      # KRaft mode configuration (single node)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Network configuration - dual listeners for internal (Docker) and external (host)
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:9092,PLAINTEXT_EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT_EXTERNAL://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      # Reduce initial consumer group rebalance latency for faster startup
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # KRaft controller configuration - FIXED
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Topic defaults
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # Performance settings
      KAFKA_MESSAGE_MAX_BYTES: 10485760  # 10MB
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760  # 10MB
      KAFKA_MAX_REQUEST_SIZE: 10485760  # 10MB
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600  # 100MB

      # Logging
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 1000
      KAFKA_LOG_RETENTION_HOURS: 168

      # JVM settings
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"

    ports:
      - "29092:29092"  # external listener exposed to host
      - "9093:9093"    # controller (for completeness)
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

networks:
  kafka-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

volumes:
  kafka-data:
    driver: local 