version: '3.8'

# Shared proxy and routing services
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    profiles: ["proxy"]  # Changed from "routing" to "proxy"
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --log.level=INFO
      - --accesslog=true
      - --providers.file.directory=/dynamic
      - --providers.file.watch=true
      - --certificatesresolvers.letsencrypt.acme.email=admin@example.com
      - --certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic:/dynamic:ro
      - ./traefik/certs:/certs
      - traefik_certs:/certs/acme  # Fixed path for Let's Encrypt
    networks:
      - proxy-network
      - app-network  # Connect to main app network

# Shared volumes for certificates
volumes:
  traefik_certs:
    driver: local

# Proxy network for routing services
networks:
  proxy-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${PROXY_SUBNET:-172.28.0.0/16}
