exporters:
  loki:
    endpoint: http://localhost:31002/loki/api/v1/push
processors:
  batch:
    timeout: 10s
receivers:
  filelog:
    include:
    - infrastructure/orchestrator/dynamicconfig/container-logs.log
    start_at: beginning
service:
  pipelines:
    logs:
      exporters:
      - loki
      processors:
      - batch
      receivers:
      - filelog
